// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xd3a4b5c6e7f80912n;
export class Vec3 extends $.Struct {
  static readonly _capnp = {
    displayName: "Vec3",
    id: "a76d842d27b1543e",
    size: new $.ObjectSize(16, 0),
  };
  get x(): number {
    return $.utils.getFloat32(0, this);
  }
  set x(value: number) {
    $.utils.setFloat32(0, value, this);
  }
  get y(): number {
    return $.utils.getFloat32(4, this);
  }
  set y(value: number) {
    $.utils.setFloat32(4, value, this);
  }
  get z(): number {
    return $.utils.getFloat32(8, this);
  }
  set z(value: number) {
    $.utils.setFloat32(8, value, this);
  }
  toString(): string { return "Vec3_" + super.toString(); }
}
export class SceneObject extends $.Struct {
  static readonly _capnp = {
    displayName: "SceneObject",
    id: "938cc390b3ec90d9",
    size: new $.ObjectSize(16, 15),
  };
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  get name(): string {
    return $.utils.getText(1, this);
  }
  set name(value: string) {
    $.utils.setText(1, value, this);
  }
  /**
* box | sphere | cylinder | cone | csg | component-instance
*
*/
  get type(): string {
    return $.utils.getText(2, this);
  }
  set type(value: string) {
    $.utils.setText(2, value, this);
  }
  get layerId(): string {
    return $.utils.getText(3, this);
  }
  set layerId(value: string) {
    $.utils.setText(3, value, this);
  }
  /**
* empty string = not in a group
*
*/
  get assemblyId(): string {
    return $.utils.getText(4, this);
  }
  set assemblyId(value: string) {
    $.utils.setText(4, value, this);
  }
  /**
* empty string = not an instance
*
*/
  get compDefId(): string {
    return $.utils.getText(5, this);
  }
  set compDefId(value: string) {
    $.utils.setText(5, value, this);
  }
  get visible(): boolean {
    return $.utils.getBit(0, this);
  }
  set visible(value: boolean) {
    $.utils.setBit(0, value, this);
  }
  get locked(): boolean {
    return $.utils.getBit(1, this);
  }
  set locked(value: boolean) {
    $.utils.setBit(1, value, this);
  }
  /**
* hex string
*
*/
  get color(): string {
    return $.utils.getText(6, this);
  }
  set color(value: string) {
    $.utils.setText(6, value, this);
  }
  get opacity(): number {
    return $.utils.getFloat32(4, this);
  }
  set opacity(value: number) {
    $.utils.setFloat32(4, value, this);
  }
  get roughness(): number {
    return $.utils.getFloat32(8, this);
  }
  set roughness(value: number) {
    $.utils.setFloat32(8, value, this);
  }
  get metalness(): number {
    return $.utils.getFloat32(12, this);
  }
  set metalness(value: number) {
    $.utils.setFloat32(12, value, this);
  }
  _adoptPosition(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownPosition(): $.Orphan<Vec3> {
    return $.utils.disown(this.position);
  }
  get position(): Vec3 {
    return $.utils.getStruct(7, Vec3, this);
  }
  _hasPosition(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initPosition(): Vec3 {
    return $.utils.initStructAt(7, Vec3, this);
  }
  set position(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptRotation(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(8, this));
  }
  _disownRotation(): $.Orphan<Vec3> {
    return $.utils.disown(this.rotation);
  }
  get rotation(): Vec3 {
    return $.utils.getStruct(8, Vec3, this);
  }
  _hasRotation(): boolean {
    return !$.utils.isNull($.utils.getPointer(8, this));
  }
  _initRotation(): Vec3 {
    return $.utils.initStructAt(8, Vec3, this);
  }
  set rotation(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(8, this));
  }
  _adoptScale(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(9, this));
  }
  _disownScale(): $.Orphan<Vec3> {
    return $.utils.disown(this.scale);
  }
  get scale(): Vec3 {
    return $.utils.getStruct(9, Vec3, this);
  }
  _hasScale(): boolean {
    return !$.utils.isNull($.utils.getPointer(9, this));
  }
  _initScale(): Vec3 {
    return $.utils.initStructAt(9, Vec3, this);
  }
  set scale(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(9, this));
  }
  /**
* JSON-encoded dimensions (type-specific)
*
*/
  get dimsJson(): string {
    return $.utils.getText(10, this);
  }
  set dimsJson(value: string) {
    $.utils.setText(10, value, this);
  }
  _adoptCsgPositions(value: $.Orphan<$.List<number>>): void {
    $.utils.adopt(value, $.utils.getPointer(11, this));
  }
  _disownCsgPositions(): $.Orphan<$.List<number>> {
    return $.utils.disown(this.csgPositions);
  }
  get csgPositions(): $.List<number> {
    return $.utils.getList(11, $.Float32List, this);
  }
  _hasCsgPositions(): boolean {
    return !$.utils.isNull($.utils.getPointer(11, this));
  }
  _initCsgPositions(length: number): $.List<number> {
    return $.utils.initList(11, $.Float32List, length, this);
  }
  set csgPositions(value: $.List<number>) {
    $.utils.copyFrom(value, $.utils.getPointer(11, this));
  }
  _adoptCsgNormals(value: $.Orphan<$.List<number>>): void {
    $.utils.adopt(value, $.utils.getPointer(12, this));
  }
  _disownCsgNormals(): $.Orphan<$.List<number>> {
    return $.utils.disown(this.csgNormals);
  }
  get csgNormals(): $.List<number> {
    return $.utils.getList(12, $.Float32List, this);
  }
  _hasCsgNormals(): boolean {
    return !$.utils.isNull($.utils.getPointer(12, this));
  }
  _initCsgNormals(length: number): $.List<number> {
    return $.utils.initList(12, $.Float32List, length, this);
  }
  set csgNormals(value: $.List<number>) {
    $.utils.copyFrom(value, $.utils.getPointer(12, this));
  }
  _adoptCsgIndices(value: $.Orphan<$.List<number>>): void {
    $.utils.adopt(value, $.utils.getPointer(13, this));
  }
  _disownCsgIndices(): $.Orphan<$.List<number>> {
    return $.utils.disown(this.csgIndices);
  }
  get csgIndices(): $.List<number> {
    return $.utils.getList(13, $.Uint32List, this);
  }
  _hasCsgIndices(): boolean {
    return !$.utils.isNull($.utils.getPointer(13, this));
  }
  _initCsgIndices(length: number): $.List<number> {
    return $.utils.initList(13, $.Uint32List, length, this);
  }
  set csgIndices(value: $.List<number>) {
    $.utils.copyFrom(value, $.utils.getPointer(13, this));
  }
  get matPresetId(): string {
    return $.utils.getText(14, this);
  }
  set matPresetId(value: string) {
    $.utils.setText(14, value, this);
  }
  toString(): string { return "SceneObject_" + super.toString(); }
}
export class Layer extends $.Struct {
  static readonly _capnp = {
    displayName: "Layer",
    id: "a6cefbb459043f71",
    size: new $.ObjectSize(8, 3),
  };
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  get name(): string {
    return $.utils.getText(1, this);
  }
  set name(value: string) {
    $.utils.setText(1, value, this);
  }
  get color(): string {
    return $.utils.getText(2, this);
  }
  set color(value: string) {
    $.utils.setText(2, value, this);
  }
  get visible(): boolean {
    return $.utils.getBit(0, this);
  }
  set visible(value: boolean) {
    $.utils.setBit(0, value, this);
  }
  get locked(): boolean {
    return $.utils.getBit(1, this);
  }
  set locked(value: boolean) {
    $.utils.setBit(1, value, this);
  }
  toString(): string { return "Layer_" + super.toString(); }
}
export class Assembly extends $.Struct {
  static readonly _capnp = {
    displayName: "Assembly",
    id: "c157abd0194c8ae2",
    size: new $.ObjectSize(0, 4),
  };
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  get name(): string {
    return $.utils.getText(1, this);
  }
  set name(value: string) {
    $.utils.setText(1, value, this);
  }
  _adoptChildIds(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownChildIds(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.childIds);
  }
  get childIds(): $.List<string> {
    return $.utils.getList(2, $.TextList, this);
  }
  _hasChildIds(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initChildIds(length: number): $.List<string> {
    return $.utils.initList(2, $.TextList, length, this);
  }
  set childIds(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  get color(): string {
    return $.utils.getText(3, this);
  }
  set color(value: string) {
    $.utils.setText(3, value, this);
  }
  toString(): string { return "Assembly_" + super.toString(); }
}
/**
* Reuses the same flat fields as SceneObject (relative positioning)
*
*/
export class ComponentObject extends $.Struct {
  static readonly _capnp = {
    displayName: "ComponentObject",
    id: "f847cb326299169b",
    size: new $.ObjectSize(16, 8),
  };
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  get name(): string {
    return $.utils.getText(1, this);
  }
  set name(value: string) {
    $.utils.setText(1, value, this);
  }
  get type(): string {
    return $.utils.getText(2, this);
  }
  set type(value: string) {
    $.utils.setText(2, value, this);
  }
  get color(): string {
    return $.utils.getText(3, this);
  }
  set color(value: string) {
    $.utils.setText(3, value, this);
  }
  get opacity(): number {
    return $.utils.getFloat32(0, this);
  }
  set opacity(value: number) {
    $.utils.setFloat32(0, value, this);
  }
  get roughness(): number {
    return $.utils.getFloat32(4, this);
  }
  set roughness(value: number) {
    $.utils.setFloat32(4, value, this);
  }
  get metalness(): number {
    return $.utils.getFloat32(8, this);
  }
  set metalness(value: number) {
    $.utils.setFloat32(8, value, this);
  }
  _adoptPosition(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownPosition(): $.Orphan<Vec3> {
    return $.utils.disown(this.position);
  }
  get position(): Vec3 {
    return $.utils.getStruct(4, Vec3, this);
  }
  _hasPosition(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initPosition(): Vec3 {
    return $.utils.initStructAt(4, Vec3, this);
  }
  set position(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  _adoptRotation(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(5, this));
  }
  _disownRotation(): $.Orphan<Vec3> {
    return $.utils.disown(this.rotation);
  }
  get rotation(): Vec3 {
    return $.utils.getStruct(5, Vec3, this);
  }
  _hasRotation(): boolean {
    return !$.utils.isNull($.utils.getPointer(5, this));
  }
  _initRotation(): Vec3 {
    return $.utils.initStructAt(5, Vec3, this);
  }
  set rotation(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(5, this));
  }
  _adoptScale(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(6, this));
  }
  _disownScale(): $.Orphan<Vec3> {
    return $.utils.disown(this.scale);
  }
  get scale(): Vec3 {
    return $.utils.getStruct(6, Vec3, this);
  }
  _hasScale(): boolean {
    return !$.utils.isNull($.utils.getPointer(6, this));
  }
  _initScale(): Vec3 {
    return $.utils.initStructAt(6, Vec3, this);
  }
  set scale(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(6, this));
  }
  get dimsJson(): string {
    return $.utils.getText(7, this);
  }
  set dimsJson(value: string) {
    $.utils.setText(7, value, this);
  }
  toString(): string { return "ComponentObject_" + super.toString(); }
}
export class ComponentDef extends $.Struct {
  static readonly _capnp = {
    displayName: "ComponentDef",
    id: "b0303907b97f7cb6",
    size: new $.ObjectSize(0, 6),
  };
  static _Objects: $.ListCtor<ComponentObject>;
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  get name(): string {
    return $.utils.getText(1, this);
  }
  set name(value: string) {
    $.utils.setText(1, value, this);
  }
  get description(): string {
    return $.utils.getText(2, this);
  }
  set description(value: string) {
    $.utils.setText(2, value, this);
  }
  _adoptObjects(value: $.Orphan<$.List<ComponentObject>>): void {
    $.utils.adopt(value, $.utils.getPointer(3, this));
  }
  _disownObjects(): $.Orphan<$.List<ComponentObject>> {
    return $.utils.disown(this.objects);
  }
  get objects(): $.List<ComponentObject> {
    return $.utils.getList(3, ComponentDef._Objects, this);
  }
  _hasObjects(): boolean {
    return !$.utils.isNull($.utils.getPointer(3, this));
  }
  _initObjects(length: number): $.List<ComponentObject> {
    return $.utils.initList(3, ComponentDef._Objects, length, this);
  }
  set objects(value: $.List<ComponentObject>) {
    $.utils.copyFrom(value, $.utils.getPointer(3, this));
  }
  _adoptOrigin(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownOrigin(): $.Orphan<Vec3> {
    return $.utils.disown(this.origin);
  }
  get origin(): Vec3 {
    return $.utils.getStruct(4, Vec3, this);
  }
  _hasOrigin(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initOrigin(): Vec3 {
    return $.utils.initStructAt(4, Vec3, this);
  }
  set origin(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  get color(): string {
    return $.utils.getText(5, this);
  }
  set color(value: string) {
    $.utils.setText(5, value, this);
  }
  toString(): string { return "ComponentDef_" + super.toString(); }
}
export class Annotation extends $.Struct {
  static readonly _capnp = {
    displayName: "Annotation",
    id: "8feb15281108ac05",
    size: new $.ObjectSize(8, 6),
  };
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  /**
* label | dimension
*
*/
  get type(): string {
    return $.utils.getText(1, this);
  }
  set type(value: string) {
    $.utils.setText(1, value, this);
  }
  get text(): string {
    return $.utils.getText(2, this);
  }
  set text(value: string) {
    $.utils.setText(2, value, this);
  }
  _adoptPosition(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(3, this));
  }
  _disownPosition(): $.Orphan<Vec3> {
    return $.utils.disown(this.position);
  }
  get position(): Vec3 {
    return $.utils.getStruct(3, Vec3, this);
  }
  _hasPosition(): boolean {
    return !$.utils.isNull($.utils.getPointer(3, this));
  }
  _initPosition(): Vec3 {
    return $.utils.initStructAt(3, Vec3, this);
  }
  set position(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(3, this));
  }
  get hasTo(): boolean {
    return $.utils.getBit(0, this);
  }
  set hasTo(value: boolean) {
    $.utils.setBit(0, value, this);
  }
  _adoptTo(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownTo(): $.Orphan<Vec3> {
    return $.utils.disown(this.to);
  }
  get to(): Vec3 {
    return $.utils.getStruct(4, Vec3, this);
  }
  _hasTo(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initTo(): Vec3 {
    return $.utils.initStructAt(4, Vec3, this);
  }
  set to(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  get color(): string {
    return $.utils.getText(5, this);
  }
  set color(value: string) {
    $.utils.setText(5, value, this);
  }
  get fontSize(): number {
    return $.utils.getFloat32(4, this);
  }
  set fontSize(value: number) {
    $.utils.setFloat32(4, value, this);
  }
  toString(): string { return "Annotation_" + super.toString(); }
}
export class CameraSnapshot extends $.Struct {
  static readonly _capnp = {
    displayName: "CameraSnapshot",
    id: "8ba5afa23b2c206d",
    size: new $.ObjectSize(8, 6),
  };
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  get name(): string {
    return $.utils.getText(1, this);
  }
  set name(value: string) {
    $.utils.setText(1, value, this);
  }
  get preset(): string {
    return $.utils.getText(2, this);
  }
  set preset(value: string) {
    $.utils.setText(2, value, this);
  }
  get mode(): string {
    return $.utils.getText(3, this);
  }
  set mode(value: string) {
    $.utils.setText(3, value, this);
  }
  _adoptPosition(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownPosition(): $.Orphan<Vec3> {
    return $.utils.disown(this.position);
  }
  get position(): Vec3 {
    return $.utils.getStruct(4, Vec3, this);
  }
  _hasPosition(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initPosition(): Vec3 {
    return $.utils.initStructAt(4, Vec3, this);
  }
  set position(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  _adoptTarget(value: $.Orphan<Vec3>): void {
    $.utils.adopt(value, $.utils.getPointer(5, this));
  }
  _disownTarget(): $.Orphan<Vec3> {
    return $.utils.disown(this.target);
  }
  get target(): Vec3 {
    return $.utils.getStruct(5, Vec3, this);
  }
  _hasTarget(): boolean {
    return !$.utils.isNull($.utils.getPointer(5, this));
  }
  _initTarget(): Vec3 {
    return $.utils.initStructAt(5, Vec3, this);
  }
  set target(value: Vec3) {
    $.utils.copyFrom(value, $.utils.getPointer(5, this));
  }
  get fov(): number {
    return $.utils.getFloat32(0, this);
  }
  set fov(value: number) {
    $.utils.setFloat32(0, value, this);
  }
  get zoom(): number {
    return $.utils.getFloat32(4, this);
  }
  set zoom(value: number) {
    $.utils.setFloat32(4, value, this);
  }
  toString(): string { return "CameraSnapshot_" + super.toString(); }
}
export class SceneSettings extends $.Struct {
  static readonly _capnp = {
    displayName: "SceneSettings",
    id: "c9b25118e60e01eb",
    size: new $.ObjectSize(24, 3),
  };
  get units(): string {
    return $.utils.getText(0, this);
  }
  set units(value: string) {
    $.utils.setText(0, value, this);
  }
  get precision(): number {
    return $.utils.getUint8(0, this);
  }
  set precision(value: number) {
    $.utils.setUint8(0, value, this);
  }
  get snapEnabled(): boolean {
    return $.utils.getBit(8, this);
  }
  set snapEnabled(value: boolean) {
    $.utils.setBit(8, value, this);
  }
  get snapDistance(): number {
    return $.utils.getFloat32(4, this);
  }
  set snapDistance(value: number) {
    $.utils.setFloat32(4, value, this);
  }
  get gridVisible(): boolean {
    return $.utils.getBit(9, this);
  }
  set gridVisible(value: boolean) {
    $.utils.setBit(9, value, this);
  }
  get axesVisible(): boolean {
    return $.utils.getBit(10, this);
  }
  set axesVisible(value: boolean) {
    $.utils.setBit(10, value, this);
  }
  get displayMode(): string {
    return $.utils.getText(1, this);
  }
  set displayMode(value: string) {
    $.utils.setText(1, value, this);
  }
  get shadowsEnabled(): boolean {
    return $.utils.getBit(11, this);
  }
  set shadowsEnabled(value: boolean) {
    $.utils.setBit(11, value, this);
  }
  get outlineEnabled(): boolean {
    return $.utils.getBit(12, this);
  }
  set outlineEnabled(value: boolean) {
    $.utils.setBit(12, value, this);
  }
  get sobelEnabled(): boolean {
    return $.utils.getBit(13, this);
  }
  set sobelEnabled(value: boolean) {
    $.utils.setBit(13, value, this);
  }
  get aoEnabled(): boolean {
    return $.utils.getBit(14, this);
  }
  set aoEnabled(value: boolean) {
    $.utils.setBit(14, value, this);
  }
  get sunAzimuth(): number {
    return $.utils.getFloat32(8, this);
  }
  set sunAzimuth(value: number) {
    $.utils.setFloat32(8, value, this);
  }
  get sunElevation(): number {
    return $.utils.getFloat32(12, this);
  }
  set sunElevation(value: number) {
    $.utils.setFloat32(12, value, this);
  }
  get sunIntensity(): number {
    return $.utils.getFloat32(16, this);
  }
  set sunIntensity(value: number) {
    $.utils.setFloat32(16, value, this);
  }
  get sectionEnabled(): boolean {
    return $.utils.getBit(15, this);
  }
  set sectionEnabled(value: boolean) {
    $.utils.setBit(15, value, this);
  }
  get sectionAxis(): string {
    return $.utils.getText(2, this);
  }
  set sectionAxis(value: string) {
    $.utils.setText(2, value, this);
  }
  get sectionOffset(): number {
    return $.utils.getFloat32(20, this);
  }
  set sectionOffset(value: number) {
    $.utils.setFloat32(20, value, this);
  }
  toString(): string { return "SceneSettings_" + super.toString(); }
}
export class SceneData extends $.Struct {
  static readonly _capnp = {
    displayName: "SceneData",
    id: "e87dd0413a5cff3a",
    size: new $.ObjectSize(0, 12),
  };
  static _Objects: $.ListCtor<SceneObject>;
  static _Layers: $.ListCtor<Layer>;
  static _Assemblies: $.ListCtor<Assembly>;
  static _ComponentDefs: $.ListCtor<ComponentDef>;
  static _Snapshots: $.ListCtor<CameraSnapshot>;
  static _Annotations: $.ListCtor<Annotation>;
  get version(): string {
    return $.utils.getText(0, this);
  }
  set version(value: string) {
    $.utils.setText(0, value, this);
  }
  get name(): string {
    return $.utils.getText(1, this);
  }
  set name(value: string) {
    $.utils.setText(1, value, this);
  }
  _adoptObjects(value: $.Orphan<$.List<SceneObject>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownObjects(): $.Orphan<$.List<SceneObject>> {
    return $.utils.disown(this.objects);
  }
  get objects(): $.List<SceneObject> {
    return $.utils.getList(2, SceneData._Objects, this);
  }
  _hasObjects(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initObjects(length: number): $.List<SceneObject> {
    return $.utils.initList(2, SceneData._Objects, length, this);
  }
  set objects(value: $.List<SceneObject>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  _adoptLayerOrder(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(3, this));
  }
  _disownLayerOrder(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.layerOrder);
  }
  get layerOrder(): $.List<string> {
    return $.utils.getList(3, $.TextList, this);
  }
  _hasLayerOrder(): boolean {
    return !$.utils.isNull($.utils.getPointer(3, this));
  }
  _initLayerOrder(length: number): $.List<string> {
    return $.utils.initList(3, $.TextList, length, this);
  }
  set layerOrder(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(3, this));
  }
  _adoptLayers(value: $.Orphan<$.List<Layer>>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownLayers(): $.Orphan<$.List<Layer>> {
    return $.utils.disown(this.layers);
  }
  get layers(): $.List<Layer> {
    return $.utils.getList(4, SceneData._Layers, this);
  }
  _hasLayers(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initLayers(length: number): $.List<Layer> {
    return $.utils.initList(4, SceneData._Layers, length, this);
  }
  set layers(value: $.List<Layer>) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  _adoptAssemblies(value: $.Orphan<$.List<Assembly>>): void {
    $.utils.adopt(value, $.utils.getPointer(5, this));
  }
  _disownAssemblies(): $.Orphan<$.List<Assembly>> {
    return $.utils.disown(this.assemblies);
  }
  get assemblies(): $.List<Assembly> {
    return $.utils.getList(5, SceneData._Assemblies, this);
  }
  _hasAssemblies(): boolean {
    return !$.utils.isNull($.utils.getPointer(5, this));
  }
  _initAssemblies(length: number): $.List<Assembly> {
    return $.utils.initList(5, SceneData._Assemblies, length, this);
  }
  set assemblies(value: $.List<Assembly>) {
    $.utils.copyFrom(value, $.utils.getPointer(5, this));
  }
  _adoptComponentDefs(value: $.Orphan<$.List<ComponentDef>>): void {
    $.utils.adopt(value, $.utils.getPointer(6, this));
  }
  _disownComponentDefs(): $.Orphan<$.List<ComponentDef>> {
    return $.utils.disown(this.componentDefs);
  }
  get componentDefs(): $.List<ComponentDef> {
    return $.utils.getList(6, SceneData._ComponentDefs, this);
  }
  _hasComponentDefs(): boolean {
    return !$.utils.isNull($.utils.getPointer(6, this));
  }
  _initComponentDefs(length: number): $.List<ComponentDef> {
    return $.utils.initList(6, SceneData._ComponentDefs, length, this);
  }
  set componentDefs(value: $.List<ComponentDef>) {
    $.utils.copyFrom(value, $.utils.getPointer(6, this));
  }
  _adoptSettings(value: $.Orphan<SceneSettings>): void {
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownSettings(): $.Orphan<SceneSettings> {
    return $.utils.disown(this.settings);
  }
  get settings(): SceneSettings {
    return $.utils.getStruct(7, SceneSettings, this);
  }
  _hasSettings(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initSettings(): SceneSettings {
    return $.utils.initStructAt(7, SceneSettings, this);
  }
  set settings(value: SceneSettings) {
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptSnapshots(value: $.Orphan<$.List<CameraSnapshot>>): void {
    $.utils.adopt(value, $.utils.getPointer(8, this));
  }
  _disownSnapshots(): $.Orphan<$.List<CameraSnapshot>> {
    return $.utils.disown(this.snapshots);
  }
  get snapshots(): $.List<CameraSnapshot> {
    return $.utils.getList(8, SceneData._Snapshots, this);
  }
  _hasSnapshots(): boolean {
    return !$.utils.isNull($.utils.getPointer(8, this));
  }
  _initSnapshots(length: number): $.List<CameraSnapshot> {
    return $.utils.initList(8, SceneData._Snapshots, length, this);
  }
  set snapshots(value: $.List<CameraSnapshot>) {
    $.utils.copyFrom(value, $.utils.getPointer(8, this));
  }
  _adoptAnnotations(value: $.Orphan<$.List<Annotation>>): void {
    $.utils.adopt(value, $.utils.getPointer(9, this));
  }
  _disownAnnotations(): $.Orphan<$.List<Annotation>> {
    return $.utils.disown(this.annotations);
  }
  get annotations(): $.List<Annotation> {
    return $.utils.getList(9, SceneData._Annotations, this);
  }
  _hasAnnotations(): boolean {
    return !$.utils.isNull($.utils.getPointer(9, this));
  }
  _initAnnotations(length: number): $.List<Annotation> {
    return $.utils.initList(9, SceneData._Annotations, length, this);
  }
  set annotations(value: $.List<Annotation>) {
    $.utils.copyFrom(value, $.utils.getPointer(9, this));
  }
  get createdAt(): string {
    return $.utils.getText(10, this);
  }
  set createdAt(value: string) {
    $.utils.setText(10, value, this);
  }
  get updatedAt(): string {
    return $.utils.getText(11, this);
  }
  set updatedAt(value: string) {
    $.utils.setText(11, value, this);
  }
  toString(): string { return "SceneData_" + super.toString(); }
}
/**
* Root message wrapper — contains the scene plus format metadata
*
*/
export class SceneFile extends $.Struct {
  static readonly _capnp = {
    displayName: "SceneFile",
    id: "af137636915dbb7e",
    size: new $.ObjectSize(8, 2),
    defaultFormatVersion: $.getUint16Mask(1)
  };
  get formatVersion(): number {
    return $.utils.getUint16(0, this, SceneFile._capnp.defaultFormatVersion);
  }
  set formatVersion(value: number) {
    $.utils.setUint16(0, value, this, SceneFile._capnp.defaultFormatVersion);
  }
  _adoptScene(value: $.Orphan<SceneData>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownScene(): $.Orphan<SceneData> {
    return $.utils.disown(this.scene);
  }
  /**
* debugJson is non-empty when debug serialization is active
*
*/
  get scene(): SceneData {
    return $.utils.getStruct(0, SceneData, this);
  }
  _hasScene(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initScene(): SceneData {
    return $.utils.initStructAt(0, SceneData, this);
  }
  set scene(value: SceneData) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  get debugJson(): string {
    return $.utils.getText(1, this);
  }
  set debugJson(value: string) {
    $.utils.setText(1, value, this);
  }
  toString(): string { return "SceneFile_" + super.toString(); }
}
ComponentDef._Objects = $.CompositeList(ComponentObject);
SceneData._Objects = $.CompositeList(SceneObject);
SceneData._Layers = $.CompositeList(Layer);
SceneData._Assemblies = $.CompositeList(Assembly);
SceneData._ComponentDefs = $.CompositeList(ComponentDef);
SceneData._Snapshots = $.CompositeList(CameraSnapshot);
SceneData._Annotations = $.CompositeList(Annotation);
